name: app_movil_innpulse
description: "Aplicación para la gestion de hoteles InnPulse."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  dio: ^5.4.0
  go_router: ^13.0.0
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  cached_network_image: ^3.3.1
  
  # Geolocalización y Mapas
  geolocator: ^13.0.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  # Firebase para notificaciones push
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/img/
    - lib/assets/splash_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/splash_logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: lib/assets/splash_logo.png
  android: true
  ios: true